export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_MINIFICATION_SETTING = 'SET_MINIFICATION_SETTING';
export const SET_CONCATENATION_SETTING = 'SET_CONCATENATION_SETTING';
export const SET_IMAGE_OPTIMIZATION_SETTING = 'SET_IMAGE_OPTIMIZATION_SETTING';
export const SET_IMAGE_FORMAT_SETTING = 'SET_IMAGE_FORMAT_SETTING';

export const ADD_MINIFICATION_EXCLUSION = 'ADD_MINIFICATION_EXCLUSION';
export const UPDATE_MINIFICATION_EXCLUSION = 'UPDATE_MINIFICATION_EXCLUSION';
export const DELETE_MINIFICATION_EXCLUSION = 'DELETE_MINIFICATION_EXCLUSION';

export const ADD_CONCATENATION_EXCLUSION = 'ADD_CONCATENATION_EXCLUSION';
export const UPDATE_CONCATENATION_EXCLUSION = 'UPDATE_CONCATENATION_EXCLUSION';
export const DELETE_CONCATENATION_EXCLUSION = 'DELETE_CONCATENATION_EXCLUSION';

export const ADD_IMAGE_OPTIMIZATION_EXCLUSION = 'ADD_IMAGE_OPTIMIZATION_EXCLUSION';
export const UPDATE_IMAGE_OPTIMIZATION_EXCLUSION = 'UPDATE_IMAGE_OPTIMIZATION_EXCLUSION';
export const DELETE_IMAGE_OPTIMIZATION_EXCLUSION = 'DELETE_IMAGE_OPTIMIZATION_EXCLUSION';

export const SET_BACKGROUND_PROCESSES = 'SET_BACKGROUND_PROCESSES';
